"""empty message

Revision ID: f74d7c79e41a
Revises: 702cbd1d7dfd
Create Date: 2024-09-09 04:02:19.810788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74d7c79e41a'
down_revision = '702cbd1d7dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comuna', sa.String(length=50), nullable=False))
        batch_op.drop_column('comuna_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comuna_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('comuna')

    # ### end Alembic commands ###
